config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from wramais.pesquisa.views import PesquisaRamaisJsonView
from autentica.util.mixin import CMCLoginRequired

urlpatterns = [

    url(r'^cadastro/', include('wramais.cadastro.urls', namespace='cadastro')),
    url(r'^autentica/', include('autentica.urls', namespace='autentica')),
    url(r'^relatorios/', include('wramais.relatorios.urls', namespace='relatorios')),
    url(r'^pesquisa/', include('wramais.pesquisa.urls', namespace='pesquisa')),
    url(r'^$', PesquisaRamaisJsonView),


    url(settings.ADMIN_URL, admin.site.urls),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns += [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ]

wramais/cadastro/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^$', views.CadastroRamaisIndexView.as_view(template_name='cadastro/index.html'), name='index'),
	url(r'^novo/$', views.CadastroRamaisCreateView.as_view(template_name='cadastro/new.html'), name='ramal-novo'),
	url(r'^altera/(?P<pk>[0-9]+)/$', views.CadastroRamaisUpdateView.as_view(template_name='cadastro/update.html'), name='ramal-altera'),
	url(r'^exclui/(?P<pk>[0-9]+)/$', views.CadastroRamaisDeleteView.as_view(), name='ramal-exclui'),
]

wramais/pesquisa/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.PesquisaRamaisJsonView),
]

wramais/relatorios/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
	url(r'^hierarquizado/$', views.RelatorioHierarquizadoView.as_view(template_name='relatorios/hierarquizado.html'), name='relatorio-hierarquizado'),
]

wramais/cadastro/models.py
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

#---------------------------------------------------------------------------------------------
# Model para a tabela RAMAL
#---------------------------------------------------------------------------------------------
@python_2_unicode_compatible
class Ramal(models.Model):	

	setor = models.IntegerField()
	numero = models.CharField(max_length=4)
	principal = models.BooleanField(default=False)

	def __unicode__(self):
		return self.numero

	def __str__(self):
		return self.numero

wramais/cadastro/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, CharField, DecimalField, DateField, BooleanField
from django.forms.models import inlineformset_factory
from django.forms import formsets, models
from django.forms.models import modelformset_factory
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Div, Button, HTML, ButtonHolder
from crispy_forms.bootstrap import (PrependedText, PrependedAppendedText, FormActions, AppendedText)
from crispy_forms.bootstrap import StrictButton
from django.conf import settings
from decimal import Decimal
from django import forms

from .models import Ramal

from datetime import datetime

class RamalPesquisaForm(forms.Form):
	pass

class RamalForm(forms.ModelForm):
	class Meta:
		model = Ramal
		fields = ['setor', 'numero', 'principal']

	def __init__(self, *args, **kwargs):
		super(RamalForm, self).__init__(*args, **kwargs)

		self.helper = FormHelper()
		self.helper.form_tag = False
		self.helper.layout = Layout(
			Div(
				Div('setor', css_class='col-md-6',),
				Div('numero', css_class='col-md-6',),
				css_class='col-md-12 row',
			),
			Div(
				Div('principal', css_class='col-md-12',),
				css_class='col-md-12 row',
			),
		)

wramais/pesquisa/forms.py
# -*- coding: utf-8 -*-

from django.forms import ModelForm, CharField, DecimalField, DateField, BooleanField
from django.forms.models import inlineformset_factory
from django.forms import formsets, models
from django.forms.models import modelformset_factory
from django.core.exceptions import ValidationError
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout, Field, Div, Button, HTML, ButtonHolder
from crispy_forms.bootstrap import (PrependedText, PrependedAppendedText, FormActions, AppendedText)
from crispy_forms.bootstrap import StrictButton
from django.conf import settings
from decimal import Decimal
from django import forms

from wramais.cadastro.models import Ramal

from datetime import datetime

class RamalPesquisaForm(forms.Form):
	pass

wramais/cadastro/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.shortcuts import render_to_response
import json
from django.core import serializers
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib import messages

from .models import Ramal
from .forms import RamalPesquisaForm, RamalForm
from .util.seguranca.seguranca import RamaisLoginRequired

#--------------------------------------------------------------------------------------
# View para pesquisa de setores/pessoas/ramais
#--------------------------------------------------------------------------------------
class CadastroRamaisIndexView(SuccessMessageMixin, FormView):
	template_name = 'cadastro/index.html'
	form_class = RamalPesquisaForm

	def get(self, request, *args, **kwargs):
		pass

#--------------------------------------------------------------------------------------
# View para inclusão de ramais
#--------------------------------------------------------------------------------------
class CadastroRamaisCreateView(RamaisLoginRequired, SuccessMessageMixin, CreateView):
	template_name = "cadastro/new.html"
	form_class = RamalForm
	model = Ramal
	success_url = '/cadastro/'
	success_message = "Ramal criado com sucesso"

#--------------------------------------------------------------------------------------
# View para alteração de ramais
#--------------------------------------------------------------------------------------
class CadastroRamaisUpdateView(RamaisLoginRequired, SuccessMessageMixin, UpdateView):
	template_name = "cadastro/update.html"
	form_class = RamalForm
	model = Ramal
	success_url = '/cadastro/'
	success_message = "Ramal alterado com sucesso"			

#--------------------------------------------------------------------------------------
# View para exclusão de ramais
#--------------------------------------------------------------------------------------
class CadastroRamaisDeleteView(RamaisLoginRequired, SuccessMessageMixin, DeleteView):
	model = Ramal
	success_url = '/cadastro/'
	success_message = "Ramal excluído com sucesso."

	def delete(self, request, *args, **kwargs):
		messages.success(self.request, self.success_message)
		return super(CadastroRamaisDeleteView, self).delete(request, *args, **kwargs)

wramais/pesquisa/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormView
import json
from wramais.cadastro.models import Ramal
from .forms import RamalPesquisaForm
from django.db import connections
from restless.views import Endpoint
from django.shortcuts import render


def PesquisaRamaisJsonView(request):
	context = {}
	return render(request,'pesquisa/index2.html',context)

wramais/relatorios/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse
from django.core.urlresolvers import reverse_lazy
from django.core.serializers.json import DjangoJSONEncoder
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic.edit import FormView
from django.http import JsonResponse
from django.shortcuts import render_to_response
import json
from django.core import serializers
from easy_pdf.views import PDFTemplateView
from django.contrib import messages

from wramais.cadastro.models import Ramal
from wramais.cadastro.util.seguranca.seguranca import RamaisLoginRequired

class RelatorioHierarquizadoView(PDFTemplateView):
	template_name = "relatorios/hierarquizado.html"
	lista_ramais = None
	#pdf_filename = "lista_ramais.pdf"

	def get_context_data(self, **kwargs):
		pass

	def get(self, request, *args, **kwargs):
		pass

wramais/templates/pages/about.html
{% extends "base.html" %}

wramais/templates/pages/home.html
{% extends "base.html" %}
{% block userdetail %}
	<p>Bem vindo, {{user.first_name}}.</p>
{% endblock %}

wramais/templates/pages/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}


{% block title %}Ramais{% endblock %}


{% block content %}

<form action="" method="get" id="formulario">
	{% crispy form %}
</form>

<div class="col-md-12">
<div class="table-responsive">
<table id="tabela" class="table table-striped table-bordered" cellspacing="0" width="100%">
	<thead>
		<tr>
			<th>Setor</th>
			<th>Ramal</th>
			<th>Pessoa</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		{% for item in lista_ramais %}
			<tr>
				<td><a href="altera/{{ item.id }}">{{ item.setor.set_nome }}</a></td>
				<td><a href="altera/{{ item.id }}">{{ item.numero }}</a></td>
				<td><a href="altera/{{ item.id }}">{{ item.pessoa.pes_nome }}</a></td>
				<td class="text-center"><a href="deleta/{{ item.id }}"><span class="glyphicon glyphicon-trash text-danger"></span></a></td>
			</tr>
		{% endfor %}
	</tbody>
</table>
</div></div>

{% endblock %}


{% block extra_javascript %}

<script>

	$(document).ready(function () {
		$('#id_setor').on('change', function() {
    		atualizaPessoas();
    	})

    	atualizaPessoas();
	});

	function pesquisa() {
		$('#formulario').submit();
	}

	function novo() {
		$(location).attr('href','novo/');
	}


	function atualizaPessoas() {
    	$('#id_pessoa').children().remove().end().append('<option selected value="">GERAL</option>') ;
       	if ($('#id_setor option:selected').val() == '')
       		request_url = '/cadastro/api/pessoas/0';
       	else
    		request_url = '/cadastro/api/pessoas/' + $('#id_setor option:selected').val();
			$.ajax({
	      		url: request_url,
      			dataType: 'json',
      			success: function(result){
	      			var toAppend = '';
      				$.each(result, function(index, element) {
	      				if (element.id == {{form.pessoa.value}})
      						toAppend += '<option selected="selected" value="' + element.id + '">' + element.nome + '</option>';
      					else
	      					toAppend += '<option value="' + element.id + '">' + element.nome + '</option>';
      				});
      				$('#id_pessoa').append(toAppend);
      			},
      			error: function(xhr, status, error) {
	        		alert('Erro ao carregar Pessoas');
            		alert(xhr.readyState);
            		alert(status);
            		alert(error);
      			}
    		})	
    	//}
    }

</script>

{% endblock %}